# ConfoundReducer.R | v2022.09.04

# Very much a work in progress.
# Simply cuts out excess covariates that fMRIPrep generates 

ConfoundReducer <- function(PIDs,
                             dir = "/data/Uncertainty/data/deriv/pipeline_1/fmriprep",
                             runs = 2,
                             task = "uncertainty",
                             confounds = c("a_comp_cor_00","a_comp_cor_01","a_comp_cor_02",
                                           "a_comp_cor_03","a_comp_cor_04","a_comp_cor_05", 
                                           names(df)[grep(x= names(df), pattern = "^cosine*")],
                                           names(df)[grep(x= names(df), pattern = "^trans*")], 
                                           names(df)[grep(x= names(df), pattern = "^rot*")], 
                                           "framewise_displacement", "dvars", "tcompcor"),
                             motion_censor = TRUE,
                             motion_censor_thresh = 0.9
                           ){

  # Check whether this file path is valid.
  if (!dir.exists(dir)){
    stop(print(paste("Error: The filepath you provided for dir (", dir, ") does not appear to exist. This directory should ideally contain the confound files generated by fMRIPrep for each participant (It should be the level just above individual participant directories). Please respecify your filepath and try again.")))
  }

  # Check whether runs is entered validly.
  if (runs <= 0 | !is.numeric(runs) | is.na(runs)){
    stop(print(paste("Error: runs should contain the number of runs your task contains. It must be a numeric value greater than 0. Please respecify the number of runs and try again.")))
  }

  # Check whether task was entered validly.
  if (is.na(task) | is.null(task)){
    stop(print(paste("Error: task should be the name heudiconv or your preferred BIDS organizing program assigns to your task. It cannot be left undefined. Please enter something and try again.")))
  }

  # I need to return and add QA checks for censor and confound arguments

  # Dependencies
  library(assertthat)
  library(dplyr)
  library(stringr)
  source("/data/tools/stinkR/make_df.R", local = T)

  # Iterating through each of the participants
  for (PID in PIDs){
    
    # Iterate through the runs in the study
    for (Run in paste0("run-",1:runs)){
      
      # Create a variable to capture the file name for this run
      filename <- paste0(dir, "/sub-", PID, "/func/sub-", PID, "_task-", task,"_", Run,"_desc-confounds_timeseries.tsv")
      
      # Check whether this file exists, and if it doesn't, print an error and give up.
      if (!file.exists(filename)){
        print(paste("Error:", PID, "'s", Run, "file could not be located:", filename))
      }
      
      # If it does exist . . . 
      if (file.exists(filename)){
        
        # Check if the file is empty
        if (file.info(filename)$size <= 0){
          print(paste("Error:", PID,"'s ", Run,"file does not contain data:", filename))
        }
        
        # And if the file isn't empty . . .
        if (file.info(filename)$size > 0){
          
          # Read in the file as a dataframe
          df <- read.table(file = filename,
                          sep = '\t',
                          header = T,
                          na.strings = c("","NA","n/a"))
                   
          # Subset the desired columns
          df <- subset(df, select = confounds)
          
          # Check if censoring should occur
          if (motion_censor == TRUE){
              
            # Iterate through each observation in the dataframe
            for (OBS in 1:nrow(df)){
              
              # Keeping track of how many motion outliers we have
              tracker <- 0
              
               # If that observation has a FWD value greater than the threshold ...
              if (df$framewise_displacement > motion_censor_thresh){
                
                # Create a new column of zeroes
                df[,ncol(df) + 1] <- 0
                
                # Add a one for this specific observation in that column
                df[OBS, ncol(df)] <- 1
                
                # If we have fewer than 10 outliers so far
                if (tracker < 10){
                  
                  # Change the name of that column
                  names(df[ncol]) <- paste0("motion_outlier0", tracker) 
                }
                
                # If we have 10 or more outliers so far
                if (tracker > 09){
                  
                  # Change the name of that column
                  names(df[ncol]) <- paste0("motion_outlier", tracker) 
                }
                
                # Adding to the tracker
                tracker <- tracker + 1
              }
            }
          }
          
          # And then save that dataframe as a new text file within that "look_onsets" folder
          write.table(df, 
                      file = paste0(dir, "/sub-", PID, "/func/sub-", PID, "_task-", task, "_", Run,"_desc-confounds_timeseries_reduced.tsv"), 
                      sep = "\t",
                      row.names = FALSE,
                      col.names = TRUE)
        }
      } 
    }
  }
}
